sudo: required
services: 
  - docker

before_install:
  - docker build -t medladhibi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=TRUE medladhibi/react-test npm run test

after_success:
  - docker build -t medladhibi/multi-client ./client 
  - docker build -t medladhibi/multi-nginx ./nginx
  - docker build -t medladhibi/multi-server ./server
  - docker build -t medladhibi/multi-worker ./worker  

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push medladhibi/multi-client
  - docker push medladhibi/multi-nginx
  - docker push medladhibi/multi-server
  - docker push medladhibi/multi-worker 